In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('/content/cars3.csv')
df.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,paint_color,state,lat,long
0,30990,2017.0,toyota,tundra double cab sr,good,8 cylinders,gas,41124.0,clean,other,NaN,NaN,pickup,red,al,32.5900,-85.480000
1,15000,2013.0,ford,f-150 xlt,excellent,6 cylinders,gas,128000.0,clean,automatic,rwd,full-size,truck,black,al,32.5920,-85.518900
2,35000,2019.0,toyota,tacoma,excellent,6 cylinders,gas,43000.0,clean,automatic,4wd,NaN,truck,grey,al,32.6013,-85.443974
3,29990,2016.0,chevrolet,colorado,good,6 cylinders,gas,17302.0,clean,other,4wd,NaN,pickup,red,al,32.5900,-85.480000
4,38590,2011.0,chevrolet,corvette,good,8 cylinders,gas,30237.0,clean,other,rwd,NaN,other,red,al,32.5900,-85.480000

In [27]:
df.isnull().sum()

price                0
year              1074
manufacturer     15938
model             4679
condition       118936
cylinders       130384
fuel              2117
odometer          1852
title_status      6490
transmission      1438
drive            98549
size            228493
type             67204
paint_color      93900
state                0
lat               2825
long              2825
dtype: int64

In [28]:
# ubstract the year column by year 2023 and rewrite the year column in df

df['year'] = 2023 - df['year']
df.head(25)

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,paint_color,state,lat,long
0,30990,6.0,toyota,tundra double cab sr,good,8 cylinders,gas,41124.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
1,15000,10.0,ford,f-150 xlt,excellent,6 cylinders,gas,128000.0,clean,automatic,rwd,full-size,truck,black,al,32.592000,-85.518900
2,35000,4.0,toyota,tacoma,excellent,6 cylinders,gas,43000.0,clean,automatic,4wd,NaN,truck,grey,al,32.601300,-85.443974
3,29990,7.0,chevrolet,colorado,good,6 cylinders,gas,17302.0,clean,other,4wd,NaN,pickup,red,al,32.590000,-85.480000
4,38590,12.0,chevrolet,corvette,good,8 cylinders,gas,30237.0,clean,other,rwd,NaN,other,red,al,32.590000,-85.480000
5,4500,31.0,jeep,cherokee,excellent,6 cylinders,gas,192000.0,clean,automatic,4wd,NaN,NaN,NaN,al,32.645400,-85.378300
6,32990,6.0,jeep,wrangler,good,6 cylinders,gas,30041.0,clean,other,4wd,NaN,other,silver,al,32.590000,-85.480000
7,30990,7.0,chevrolet,colorado,good,NaN,other,34940.0,clean,other,4wd,NaN,pickup,blue,al,32.590000,-85.480000
8,27990,9.0,toyota,tacoma access cab pickup,good,NaN,other,17805.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
9,37990,7.0,chevrolet,camaro,good,8 cylinders,gas,9704.0,clean,other,rwd,NaN,coupe,red,al,32.590000,-85.480000
10,33590,9.0,toyota,tundra crewmax sr5 pickup,good,NaN,other,55251.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
11,30990,4.0,ford,ranger supercrew xl pickup,good,NaN,other,1834.0,clean,other,NaN,NaN,pickup,black,al,32.590000,-85.480000
12,27990,5.0,nissan,frontier crew cab pro-4x,good,6 cylinders,gas,37332.0,clean,other,4wd,NaN,pickup,silver,al,32.590000,-85.480000
13,34590,5.0,ford,f150 super cab xl pickup 4d,good,6 cylinders,gas,20856.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000
14,30590,7.0,toyota,tacoma double cab sr5,good,NaN,other,30176.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
15,32990,3.0,jeep,wrangler,good,NaN,gas,20581.0,clean,other,4wd,NaN,SUV,silver,al,32.590000,-85.480000
16,38990,3.0,ford,f150 supercrew cab xlt,good,6 cylinders,gas,12231.0,clean,other,NaN,NaN,pickup,NaN,al,32.590000,-85.480000
17,22590,6.0,ram,1500 model,good,8 cylinders,gas,39508.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000
18,31590,3.0,mazda,mx-5 miata club,good,NaN,gas,2195.0,clean,other,rwd,NaN,other,NaN,al,32.590000,-85.480000
19,27990,3.0,ford,ranger supercab xl pickup,good,NaN,gas,10688.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000
20,31590,4.0,cadillac,xts,good,NaN,other,12102.0,clean,other,fwd,NaN,hatchback,black,al,32.590000,-85.480000
21,19900,19.0,ford,f250 super duty,good,8 cylinders,diesel,88000.0,clean,automatic,4wd,full-size,pickup,blue,al,32.547500,-85.468200
22,26990,7.0,ford,f150 regular cab xl pickup,good,6 cylinders,gas,14230.0,clean,other,NaN,NaN,pickup,black,al,32.590000,-85.480000
23,14000,11.0,honda,odyssey,excellent,6 cylinders,gas,95000.0,clean,automatic,fwd,full-size,mini-van,silver,al,32.628739,-85.461820
24,28590,5.0,ram,1500 model,good,6 cylinders,other,30047.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000

In [29]:
# Replace 'cylinders ' from string values in the 'cylinders' column
df['cylinders'] = df['cylinders'].apply(lambda x: x.replace(' cylinders', '') if isinstance(x, str) else x)

In [30]:
df.head(25)

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,size,type,paint_color,state,lat,long
0,30990,6.0,toyota,tundra double cab sr,good,8,gas,41124.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
1,15000,10.0,ford,f-150 xlt,excellent,6,gas,128000.0,clean,automatic,rwd,full-size,truck,black,al,32.592000,-85.518900
2,35000,4.0,toyota,tacoma,excellent,6,gas,43000.0,clean,automatic,4wd,NaN,truck,grey,al,32.601300,-85.443974
3,29990,7.0,chevrolet,colorado,good,6,gas,17302.0,clean,other,4wd,NaN,pickup,red,al,32.590000,-85.480000
4,38590,12.0,chevrolet,corvette,good,8,gas,30237.0,clean,other,rwd,NaN,other,red,al,32.590000,-85.480000
5,4500,31.0,jeep,cherokee,excellent,6,gas,192000.0,clean,automatic,4wd,NaN,NaN,NaN,al,32.645400,-85.378300
6,32990,6.0,jeep,wrangler,good,6,gas,30041.0,clean,other,4wd,NaN,other,silver,al,32.590000,-85.480000
7,30990,7.0,chevrolet,colorado,good,NaN,other,34940.0,clean,other,4wd,NaN,pickup,blue,al,32.590000,-85.480000
8,27990,9.0,toyota,tacoma access cab pickup,good,NaN,other,17805.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
9,37990,7.0,chevrolet,camaro,good,8,gas,9704.0,clean,other,rwd,NaN,coupe,red,al,32.590000,-85.480000
10,33590,9.0,toyota,tundra crewmax sr5 pickup,good,NaN,other,55251.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
11,30990,4.0,ford,ranger supercrew xl pickup,good,NaN,other,1834.0,clean,other,NaN,NaN,pickup,black,al,32.590000,-85.480000
12,27990,5.0,nissan,frontier crew cab pro-4x,good,6,gas,37332.0,clean,other,4wd,NaN,pickup,silver,al,32.590000,-85.480000
13,34590,5.0,ford,f150 super cab xl pickup 4d,good,6,gas,20856.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000
14,30590,7.0,toyota,tacoma double cab sr5,good,NaN,other,30176.0,clean,other,NaN,NaN,pickup,red,al,32.590000,-85.480000
15,32990,3.0,jeep,wrangler,good,NaN,gas,20581.0,clean,other,4wd,NaN,SUV,silver,al,32.590000,-85.480000
16,38990,3.0,ford,f150 supercrew cab xlt,good,6,gas,12231.0,clean,other,NaN,NaN,pickup,NaN,al,32.590000,-85.480000
17,22590,6.0,ram,1500 model,good,8,gas,39508.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000
18,31590,3.0,mazda,mx-5 miata club,good,NaN,gas,2195.0,clean,other,rwd,NaN,other,NaN,al,32.590000,-85.480000
19,27990,3.0,ford,ranger supercab xl pickup,good,NaN,gas,10688.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000
20,31590,4.0,cadillac,xts,good,NaN,other,12102.0,clean,other,fwd,NaN,hatchback,black,al,32.590000,-85.480000
21,19900,19.0,ford,f250 super duty,good,8,diesel,88000.0,clean,automatic,4wd,full-size,pickup,blue,al,32.547500,-85.468200
22,26990,7.0,ford,f150 regular cab xl pickup,good,6,gas,14230.0,clean,other,NaN,NaN,pickup,black,al,32.590000,-85.480000
23,14000,11.0,honda,odyssey,excellent,6,gas,95000.0,clean,automatic,fwd,full-size,mini-van,silver,al,32.628739,-85.461820
24,28590,5.0,ram,1500 model,good,6,other,30047.0,clean,other,NaN,NaN,pickup,white,al,32.590000,-85.480000

In [31]:
# SInce size has more than half null values we remove it from the dataframe.
df = df.drop('size', axis=1)

In [32]:
# It does not make sense to fill the nan values present in year columns. As it is one of major price indicator for used cars. Filling it with synthetic values might mess up the model.
df = df.dropna(subset=['year'])

In [33]:
df.shape

(315411, 16)

In [34]:
# understanding dataset stats
df.describe()

              price           year      odometer            lat           long
count  3.154110e+05  315411.000000  3.136000e+05  312626.000000  312626.000000
mean   9.563284e+04      11.732628  9.712415e+04      38.426114     -94.232134
std    1.416888e+07       9.124702  2.028360e+05       5.857772      18.235658
min    1.000000e+00       1.000000  0.000000e+00     -84.122245    -159.827728
25%    6.999000e+03       6.000000  3.715200e+04      34.436702    -110.978729
50%    1.499000e+04      10.000000  8.500000e+04      39.190000     -87.762273
75%    2.699000e+04      15.000000  1.330620e+05      42.335300     -80.684450
max    3.736929e+09     123.000000  1.000000e+07      82.390818     173.885502

In [35]:
# list all categorical features

categorical_features = df.select_dtypes(include=['object']).columns.tolist()
print(categorical_features)

['manufacturer', 'model', 'condition', 'cylinders', 'fuel', 'title_status', 'transmission', 'drive', 'type', 'paint_color', 'state']

In [36]:
# splitting the df into train and test

from sklearn.model_selection import train_test_split

train_data, test_data= train_test_split(df, test_size=0.2, random_state=42)

In [37]:
train_data.shape

(252328, 16)

In [38]:
test_data.shape

(63083, 16)

In [39]:
from sklearn.impute import SimpleImputer

# Create an instance of SimpleImputer
imputer = SimpleImputer(strategy='most_frequent')  # or any other strategy you prefer

# Fit and transform the training data
train_imputed = imputer.fit_transform(train_data)

# Transform the test data using the same imputer
test_imputed = imputer.transform(test_data)

In [40]:
train_imputed[:20]

array([[15897, 5.0, 'chevrolet', 'malibu', 'good', '4', 'gas', 65950.0,
        'clean', 'other', 'fwd', 'sedan', 'grey', 'al', 34.2056,
        -86.85834],
       [24988, 6.0, 'ford', 'f-350', 'good', '6', 'diesel', 121251.0,
        'clean', 'automatic', 'fwd', 'other', 'white', 'az', 33.534798,
        -112.180236],
       [27999, 7.0, 'jeep', 'wrangler', 'excellent', '6', 'gas', 81899.0,
        'clean', 'automatic', '4wd', 'SUV', 'white', 'oh', 41.038965,
        -81.575742],
       [3500, 43.0, 'ford', 'f100', 'good', '6', 'gas', 83220.0, 'clean',
        'manual', '4wd', 'pickup', 'red', 'ks', 39.2458, -96.6336],
       [7699, 13.0, 'mazda', 'mazda6 4dr sdn auto i touring', 'good',
        '4', 'gas', 131370.0, 'clean', 'automatic', 'fwd', 'sedan',
        'grey', 'wa', 46.236677, -119.129454],
       [8495, 13.0, 'toyota', 'rav 4', 'like new', '4', 'gas', 161420.0,
        'clean', 'automatic', '4wd', 'sedan', 'white', 'ca', 32.805136,
        -117.21326],
       [18700, 6.0, 'dodge', 'journey', 'like new', '6', 'gas', 33920.0,
        'clean', 'automatic', 'fwd', 'SUV', 'custom', 'fl', 27.234099,
        -80.829894],
       [17590, 6.0, 'kia', 'optima plug-in hybrid ex', 'good', '6',
        'other', 36079.0, 'clean', 'other', '4wd', 'sedan', 'black',
        'ok', 36.12, -95.91],
       [9590, 13.0, 'kia', 'forte sx sedan 4d', 'good', '6', 'gas',
        85615.0, 'clean', 'other', 'fwd', 'sedan', 'silver', 'nc', 35.73,
        -81.32],
       [25990, 14.0, 'ford', 'f550 super duty', 'excellent', '10', 'gas',
        166388.0, 'clean', 'automatic', 'rwd', 'truck', 'white', 'ga',
        27.2866, -82.477],
       [2000, 28.0, 'nissan', 'pathfinder', 'good', '6', 'gas', 228127.0,
        'clean', 'manual', '4wd', 'SUV', 'blue', 'fl', 29.770834,
        -82.283186],
       [44900, 9.0, 'ram', '2500 model', 'good', '6', 'diesel', 152034.0,
        'clean', 'automatic', '4wd', 'sedan', 'white', 'tx', 30.663,
        -97.9316],
       [261, 6.0, 'dodge', 'caravan', 'good', '6', 'gas', 63340.0,
        'clean', 'automatic', 'fwd', 'sedan', 'white', 'or', 44.973187,
        -123.018138],
       [18590, 5.0, 'hyundai', 'elantra', 'good', '6', 'gas', 36214.0,
        'clean', 'other', 'fwd', 'hatchback', 'black', 'az', 33.44,
        -111.8],
       [32999, 6.0, 'ram', '1500 model', 'good', '6', 'gas', 21576.0,
        'clean', 'automatic', '4wd', 'truck', 'grey', 'or', 43.61974,
        -116.29469],
       [11495, 11.0, 'bmw', 'x5', 'good', '6', 'gas', 129710.0, 'clean',
        'automatic', '4wd', 'SUV', 'black', 'dc', 38.481752, -77.387518],
       [33995, 6.0, 'ford', 'mustang gt', 'good', '8', 'gas', 35932.0,
        'clean', 'automatic', '4wd', 'coupe', 'black', 'ks', 39.0152,
        -94.2604],
       [25365, 6.0, 'bmw', '3 series', 'good', '4', 'gas', 16664.0,
        'clean', 'automatic', '4wd', 'sedan', 'white', 'or', 45.49379,
        -122.774715],
       [29995, 6.0, 'lincoln', 'mkx', 'good', '6', 'gas', 41024.0,
        'clean', 'automatic', 'fwd', 'SUV', 'white', 'tx', 29.148519,
        -98.875934],
       [4490, 17.0, 'nissan', 'murano-awd', 'good', '6', 'gas', 104904.0,
        'clean', 'automatic', '4wd', 'SUV', 'grey', 'me', 42.8285,
        -71.6606]], dtype=object)

In [41]:
test_imputed[:20]

array([[14500, 28.0, 'ford', 'bronco xlt', 'good', '8', 'gas', 127750.0,
        'clean', 'automatic', '4wd', 'sedan', 'white', 'co', 38.819247,
        -104.839096],
       [6995, 13.0, 'chevrolet', 'traverse', 'good', '6', 'gas',
        135362.0, 'clean', 'automatic', '4wd', 'sedan', 'white', 'mi',
        43.1824, -84.1122],
       [6950, 20.0, 'mercedes-benz', 's-class', 'like new', '4', 'gas',
        61121.0, 'clean', 'automatic', 'rwd', 'convertible', 'black',
        'fl', 27.888284, -82.744474],
       [27990, 5.0, 'cadillac', 'cts', 'good', '6', 'gas', 26570.0,
        'clean', 'other', '4wd', 'sedan', 'silver', 'ga', 32.51, -84.87],
       [36000, 6.0, 'jeep', 'wrangler', 'excellent', '6', 'gas', 45000.0,
        'clean', 'automatic', '4wd', 'SUV', 'blue', 'ak', 64.878089,
        -148.214529],
       [4500, 35.0, 'nissan', 'pulsar', 'good', '4', 'gas', 169999.0,
        'clean', 'manual', 'fwd', 'sedan', 'red', 'tx', 31.0065, -97.841],
       [36990, 5.0, 'audi', 's5 premium plus coupe 2d', 'good', '6',
        'gas', 46298.0, 'clean', 'other', '4wd', 'coupe', 'white', 'dc',
        38.89, -77.03],
       [10995, 10.0, 'ford', 'explorer', 'excellent', '6', 'gas',
        138269.0, 'clean', 'automatic', '4wd', 'SUV', 'green', 'ri',
        41.668966, -70.269642],
       [5995, 18.0, 'ford', 'ranger', 'good', '6', 'gas', 101000.0,
        'clean', 'manual', '4wd', 'sedan', 'white', 'ri', 41.9296,
        -71.3009],
       [10750, 10.0, 'mercedes-benz', 'e-class', 'good', '6', 'gas',
        176672.0, 'clean', 'automatic', '4wd', 'sedan', 'black', 'il',
        38.7622, -90.5471],
       [18990, 4.0, 'dodge', 'journey', 'good', '6', 'other', 5378.0,
        'clean', 'other', 'fwd', 'SUV', 'white', 'wi', 44.26, -88.39],
       [6900, 10.0, 'ford', 'escape se ecoboost', 'excellent', '4',
        'gas', 128000.0, 'clean', 'automatic', '4wd', 'SUV', 'black',
        'mi', 42.326972, -83.272634],
       [29999, 10.0, 'jeep', 'wrangler', 'good', '6', 'gas', 96447.0,
        'clean', 'manual', '4wd', 'SUV', 'black', 'wa', 47.526981,
        -122.699745],
       [163540, 3.0, 'mercedes-benz', 'wrangler', 'good', '8', 'other',
        6318.0, 'clean', 'automatic', 'fwd', 'other', 'white', 'nm',
        45.494265, -122.579192],
       [34990, 3.0, 'buick', 'enclave essence sport', 'good', '6', 'gas',
        33333.0, 'clean', 'other', 'fwd', 'other', 'white', 'nm', 35.11,
        -106.62],
       [16999, 4.0, 'mitsubishi', 'eclipse cross es 4x4', 'good', '6',
        'gas', 38790.0, 'clean', 'automatic', '4wd', 'SUV', 'silver',
        'ut', 43.61974, -116.29469],
       [167, 8.0, 'chevrolet', 'malibu', 'good', '6', 'gas', 79539.0,
        'clean', 'automatic', '4wd', 'sedan', 'blue', 'nc', 34.705098,
        -77.158268],
       [20995, 8.0, 'chevrolet', 'camaro', 'excellent', '6', 'gas',
        76968.0, 'clean', 'automatic', '4wd', 'sedan', 'white', 'tx',
        29.3374, -98.5393],
       [6850, 10.0, 'kia', 'optima lx', 'excellent', '4', 'gas',
        144272.0, 'clean', 'automatic', '4wd', 'sedan', 'white', 'sc',
        35.3613, -82.4264],
       [8900, 13.0, 'ford', 'f-150', 'excellent', '8', 'gas', 173000.0,
        'clean', 'automatic', 'rwd', 'pickup', 'white', 'fl', 27.4265,
        -81.31258]], dtype=object)

In [42]:
# convert the train_imputed and test_imputed array to dataframe

train_imputed_df = pd.DataFrame(train_imputed, columns=df.columns)
test_imputed_df = pd.DataFrame(test_imputed, columns=df.columns)

In [43]:
train_imputed_df.head()

,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,type,paint_color,state,lat,long
0,15897,5.0,chevrolet,malibu,good,4,gas,65950.0,clean,other,fwd,sedan,grey,al,34.2056,-86.85834
1,24988,6.0,ford,f-350,good,6,diesel,121251.0,clean,automatic,fwd,other,white,az,33.534798,-112.180236
2,27999,7.0,jeep,wrangler,excellent,6,gas,81899.0,clean,automatic,4wd,SUV,white,oh,41.038965,-81.575742
3,3500,43.0,ford,f100,good,6,gas,83220.0,clean,manual,4wd,pickup,red,ks,39.2458,-96.6336
4,7699,13.0,mazda,mazda6 4dr sdn auto i touring,good,4,gas,131370.0,clean,automatic,fwd,sedan,grey,wa,46.236677,-119.129454

In [44]:
train_imputed_df.shape

(252328, 16)

In [45]:
train_imputed_df.to_csv('train_data.csv', index=False)

In [46]:
test_imputed_df.shape

(63083, 16)

In [47]:
test_imputed_df.to_csv('test_data.csv',index=False)